name: 'Deploy to Azure Web App'
description: 'Deploy a container to an Azure Web App'
inputs:
  app-name:
    description: 'Name of the Azure Web App'
    required: true
  resource-group:
    description: 'Name of the Azure Resource Group'
    required: true
  image-name:
    description: 'Name of the container image'
    required: true
  image-tag:
    description: 'Tag of the container image'
    required: true
  branch:
    description: 'Source Git branch, main if none specified'
    required: false
    default: 'main'
  region:
    description: 'Azure region'
    required: true
  group:
    description: 'Azure resource group'
    required: true
  azure-credentials:
    description: 'Azure subscription and resource group service principal'
    required: true
  product:
    description: 'Product name'
    required: true
  environment:
    description: 'Environment name'
    required: true
  version:
    description: 'Version'
    required: true  
  webapp:
    description: 'Azure WebApp name'
    required: true
  client-id:
    description: 'Azure Service Principal Client ID'
    required: true
  client-secret:
    description: 'Azure Service Principal Client Secret'
    required: true    

runs:
  using: "composite"
  steps:
    - name: Repository 🗃️
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Defaults ✨
      uses: azure/cli@v2.1.0
      with:
        inlineScript: |
          az configure --defaults location=${{ inputs.region }}
          az configure --defaults group=${{ inputs.group }}    

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    
    - name: CLI 📝
      run: |
        ACR_NAME=$(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv)
        echo ACR=$(az acr show -n $ACR_NAME --query loginServer -o tsv) >> $GITHUB_ENV
        echo WEBAPP=$(az resource list --resource-type 'Microsoft.Web/sites' --query '[?contains(name, `${{ inputs.webapp }}`)].name' -o tsv) >> $GITHUB_ENV
      shell: bash
    
    - name: ACR 🔐
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR }}
        username: ${{ inputs.client-id }}
        password: ${{ inputs.client-secret }}
        
    
    - name: Build and push image to ACR
      shell: bash
      run: |
          cd ${{ github.workspace }}
          docker build . -t ${{ env.ACR_NAME }}/${{ inputs.webapp }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}/${{ inputs.webapp }}:${{ github.sha }}