name: 'Deploy to Azure Web App'
description: 'Deploy a container to an Azure Web App'
inputs:
  app-name:
    description: 'Name of the Azure Web App'
    required: true
  resource-group:
    description: 'Name of the Azure Resource Group'
    required: true
  image-name:
    description: 'Name of the container image'
    required: true
  image-tag:
    description: 'Tag of the container image'
    required: true
  branch:
    description: 'Source Git branch, main if none specified'
    required: false
    default: 'main'
  region:
    description: 'Azure region'
    required: true
  group:
    description: 'Azure resource group'
    required: true
  azure-credentials:
    description: 'Azure subscription and resource group service principal'
    required: true
  product:
    description: 'Product name'
    required: true
  environment:
    description: 'Environment name'
    required: true
  version:
    description: 'Version'
    required: true  
  acr:
    description: 'Azure container registry password'
    required: true   

runs:
  using: "composite"
  steps:
    - name: Repository 🗃️
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Defaults ✨
      uses: azure/cli@v2.1.0
      with:
        inlineScript: |
          az configure --defaults location=${{ inputs.region }}
          az configure --defaults group=${{ inputs.group }}    

    - name: Azure 🔐
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    
    - name: CLI 📝
      run: |
        echo ACR=$(az acr show -n $(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv) --query loginServer -o tsv) >> $GITHUB_ENV
        echo ACR_USER=$(az acr show -n $(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv) --query name -o tsv) >> $GITHUB_ENV
        echo WEBAPP=$(az resource list --resource-type 'Microsoft.Web/sites' --query '[?contains(name, `${{ inputs.webapp }}`)].name' -o tsv) >> $GITHUB_ENV
      shell: bash
    
    - name: ACR Login 🔐
      run: |
        az acr login -n ${{ env.ACR_USER }}
      shell: bash

    
    - name: Build and push Docker image 🗃️
      shell: bash
      run: |
          cd ${{ github.workspace }}
          docker build . -t ${{ env.ACR }}/${{ inputs.app-name }}:${{ github.sha }}
          docker build . -t ${{ env.ACR }}/${{ inputs.app-name }}:latest
          docker push ${{ env.ACR }}/${{ inputs.app-name }}:latest
          docker push ${{ env.ACR }}/${{ inputs.app-name }}:${{ github.sha }}

    - name: Update Web App Container Settings 🔄
      run: |
        az webapp config container set --name ${{ env.WEBAPP }} --resource-group ${{ inputs.resource-group }} \
          --container-image-name ${{ env.ACR }}/${{ inputs.app-name }}:${{ github.sha }} \
          --container-registry-url https://${{ env.ACR }}
      shell: bash                         